/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface FaucetInterface extends ethers.utils.Interface {
  functions: {
    "c_0x747d8434(bytes32)": FunctionFragment;
    "requestToken(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "c_0x747d8434",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestToken",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "c_0x747d8434",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class Faucet extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: FaucetInterface;

  functions: {
    c_0x747d8434(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    "c_0x747d8434(bytes32)"(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<[void]>;

    requestToken(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "requestToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  c_0x747d8434(
    c__0x747d8434: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  "c_0x747d8434(bytes32)"(
    c__0x747d8434: BytesLike,
    overrides?: CallOverrides
  ): Promise<void>;

  requestToken(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "requestToken(address)"(
    _token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    c_0x747d8434(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "c_0x747d8434(bytes32)"(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    requestToken(_token: string, overrides?: CallOverrides): Promise<void>;

    "requestToken(address)"(
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    c_0x747d8434(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "c_0x747d8434(bytes32)"(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestToken(_token: string, overrides?: Overrides): Promise<BigNumber>;

    "requestToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    c_0x747d8434(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "c_0x747d8434(bytes32)"(
      c__0x747d8434: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requestToken(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "requestToken(address)"(
      _token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
