/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Faucet } from "../Faucet";

export class Faucet__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Faucet> {
    return super.deploy(overrides || {}) as Promise<Faucet>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Faucet {
    return super.attach(address) as Faucet;
  }
  connect(signer: Signer): Faucet__factory {
    return super.connect(signer) as Faucet__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Faucet {
    return new Contract(address, _abi, signerOrProvider) as Faucet;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_token",
        type: "address",
      },
    ],
    name: "requestToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610172806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063a037eca914610030575b600080fd5b61004361003e3660046100d5565b610045565b005b60405163a9059cbb60e01b815281906001600160a01b0382169063a9059cbb9061007e903390683635c9adc5dea0000090600401610123565b602060405180830381600087803b15801561009857600080fd5b505af11580156100ac573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100d09190610103565b505050565b6000602082840312156100e6578081fd5b81356001600160a01b03811681146100fc578182fd5b9392505050565b600060208284031215610114578081fd5b815180151581146100fc578182fd5b6001600160a01b0392909216825260208201526040019056fea26469706673582212208ce1b00fe3746fa797083d59c973fee57047ae52657fe8315ba8c81e8b5eec8f64736f6c63430008000033";
