/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { ChiGasSaver } from "../ChiGasSaver";

export class ChiGasSaver__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<ChiGasSaver> {
    return super.deploy(overrides || {}) as Promise<ChiGasSaver>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): ChiGasSaver {
    return super.attach(address) as ChiGasSaver;
  }
  connect(signer: Signer): ChiGasSaver__factory {
    return super.connect(signer) as ChiGasSaver__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ChiGasSaver {
    return new Contract(address, _abi, signerOrProvider) as ChiGasSaver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0xf692dbf0",
        type: "bytes32",
      },
    ],
    name: "c_0xf692dbf0",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060918061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063c9c9d93414602d575b600080fd5b605660048036036020811015604157600080fd5b81019080803590602001909291905050506058565b005b5056fea2646970667358221220155c538296e730f9427cb7a678c4a752227a998888eec6abca56b5bf6b7a727464736f6c63430007060033";
