/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IFreeFromUpTo } from "../IFreeFromUpTo";

export class IFreeFromUpTo__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFreeFromUpTo {
    return new Contract(address, _abi, signerOrProvider) as IFreeFromUpTo;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0xb9603089",
        type: "bytes32",
      },
    ],
    name: "c_0xb9603089",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "freeFromUpTo",
    outputs: [
      {
        internalType: "uint256",
        name: "freed",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
