/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { Utils } from "../Utils";

export class Utils__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<Utils> {
    return super.deploy(overrides || {}) as Promise<Utils>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Utils {
    return super.attach(address) as Utils;
  }
  connect(signer: Signer): Utils__factory {
    return super.connect(signer) as Utils__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Utils {
    return new Contract(address, _abi, signerOrProvider) as Utils;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_price",
        type: "bytes4",
      },
      {
        internalType: "uint256",
        name: "_scale",
        type: "uint256",
      },
    ],
    name: "_unpackPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610195806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c806345bbd14114610030575b600080fd5b61005d6004803603604081101561004657600080fd5b506001600160e01b0319813516906020013561006f565b60408051918252519081900360200190f35b600060f083901c61ffff60e085901c1683820261270f8211156100925761270f91505b8160005b61ffff8216156100b257600a61ffff8316049150600101610096565b8060ff1687116100f3576040805162461bcd60e51b81526020600482015260076024820152661a5b9d985b1a5960ca1b604482015290519081900360640190fd5b60008160ff16888661ffff16028161010757fe5b04905083810184811015610152576040805162461bcd60e51b815260206004820152600d60248201526c696e76616c696420707269636560981b604482015290519081900360640190fd5b999850505050505050505056fea264697066735822122032f9a35441afd17741ea271ec7c273840e53b42c57c1baa4c769f7d47959ce4164736f6c63430007060033";
